const form=document.querySelector('#rubricForm');
const inputPanel=document.querySelector('#inputPanel');
const questionPanel=document.querySelector('#questionPanel');
const resultSection=document.querySelector('#resultSection');
const questionsEl=document.querySelector('#generatedQuestions');
const output=document.querySelector('#rubricOutput');
const progress=[...document.querySelectorAll('.simple-progress span')];
const STORAGE_KEY='rubric-maker-simple-v2';
let generated=[];
let latestData=null;
const sample={subject:'사회',grade:'4학년 1학기',itemCount:'3',standard:'[4사05-01] 민주주의의 의미를 이해하고, 학교생활에서 민주주의를 실천하는 태도를 기른다.',focus:'선거 과정에 참여하는 방법과 바람직한 태도',materials:'학급 회장 선거, 후보자 공약 비교, 비밀 투표 절차',expectation:'자료를 근거로 판단하고 민주적인 참여 방법을 제안하기',maxScore:'3',commonRule:'표현이 달라도 민주적인 선거 참여의 의미와 근거가 타당하면 인정한다.'};

function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200);}
function data(){const f=new FormData(form);return Object.fromEntries([...f.entries()].map(([k,v])=>[k,String(v).trim()]));}
function setData(d){Object.entries(d).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v;});saveDraft();}
function saveDraft(){clearTimeout(saveDraft.timer);document.querySelector('#saveState').textContent='저장 중…';saveDraft.timer=setTimeout(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(data()));document.querySelector('#saveState').textContent='저장됨';},220);}
function validate(){let ok=true;[...form.querySelectorAll('[required]')].forEach(el=>{el.classList.toggle('invalid',!el.value.trim());if(!el.value.trim())ok=false;});if(!ok){form.querySelector('.invalid')?.focus();toast('별표가 있는 정보만 채워 주세요.');}return ok;}
function keywords(text){return text.replace(/\[[^\]]+\]/g,'').split(/[,.\n/]/).map(s=>s.trim()).filter(s=>s.length>2).slice(0,4);}
function makeQuestionDrafts(d){const count=Number(d.itemCount),t=d.focus.replace(/[.。]$/,'').trim(),material=d.materials||'수업에서 다룬 자료나 사례',expectation=d.expectation||'자신의 생각을 근거와 함께 표현하기',key=keywords(d.standard)[0]||t;const pool=[{type:'이해',prompt:`${t}에서 중요하게 지켜야 할 점을 한 가지 이상 쓰고, 그렇게 생각한 까닭을 설명하시오.`,element:`${t}의 핵심 의미와 까닭 설명`,evidence:`${t}의 핵심 내용, 타당한 까닭 또는 근거`},{type:'분석',prompt:`${material}을(를) 살펴보고, ${t}에 알맞은 선택을 한 뒤 자료를 근거로 판단한 까닭을 쓰시오.`,element:`자료를 근거로 ${t}에 맞게 판단하기`,evidence:`자료에서 찾은 근거, 선택 또는 판단, 근거와 판단의 논리적 연결`},{type:'적용',prompt:`${t}을(를) 바람직하게 실천하기 위해 우리 학급에서 할 수 있는 구체적인 방법을 제안하고, 기대되는 변화를 쓰시오.`,element:`${t}의 실천 방법 제안`,evidence:`실행 가능한 제안, ${key}과의 관련성, 기대되는 변화`},{type:'평가',prompt:`${t}과(와) 관련된 두 의견 중 더 타당한 의견을 고르고, ${material}을(를) 활용하여 자신의 판단을 논리적으로 쓰시오.`,element:'근거를 활용해 의견의 타당성 평가',evidence:`의견 선택, 자료 근거, ${expectation}`}];return pool.slice(0,count).map((q,i)=>({...q,id:i+1,maxScore:Number(d.maxScore)}));}
function renderQuestions(){questionsEl.innerHTML=generated.map((q,i)=>`<article class="generated-question"><div class="generated-question-head"><span>문항 ${i+1}</span><small>${escapeHtml(q.type)} 중심</small></div><label class="field"><span>문항 초안</span><textarea rows="3" data-i="${i}" data-k="prompt">${escapeHtml(q.prompt)}</textarea></label><div class="question-meta"><label class="field"><span>채점요소</span><input data-i="${i}" data-k="element" value="${escapeHtml(q.element)}"></label><label class="field"><span>기대 답안의 핵심</span><input data-i="${i}" data-k="evidence" value="${escapeHtml(q.evidence)}"></label></div></article>`).join('');questionsEl.querySelectorAll('[data-i]').forEach(el=>el.addEventListener('input',()=>{generated[Number(el.dataset.i)][el.dataset.k]=el.value.trim();}));}
function showQuestions(){inputPanel.hidden=true;questionPanel.hidden=false;resultSection.hidden=true;progress.forEach((p,i)=>p.classList.toggle('active',i===1));questionPanel.scrollIntoView({behavior:'smooth',block:'start'});}
function descriptors(q){const max=q.maxScore,points=q.evidence.split(/[,\n]/).map(s=>s.trim()).filter(Boolean),joined=points.join(', ');return Array.from({length:max+1},(_,i)=>max-i).map(score=>{if(score===0)return{score,text:'무응답이거나 문항의 요구와 관련 없는 내용을 작성한 경우'};if(score===max)return{score,text:`${joined}을(를) 모두 포함하여 문항의 요구에 맞게 정확하고 논리적으로 작성한 경우`};return{score,text:score/max>=.67?`${joined}의 대부분을 포함하고 설명의 흐름이 대체로 타당한 경우`:`${joined} 중 일부를 포함했으나 설명이나 근거가 충분하지 않은 경우`};});}
function renderRubric(d){const body=generated.map((q,qi)=>descriptors(q).map((r,ri)=>`<tr>${ri===0?`<td rowspan="${q.maxScore+1}" class="score">${qi+1}</td><td rowspan="${q.maxScore+1}" contenteditable="true"><b>${escapeHtml(q.element)}</b><br><small>${escapeHtml(q.prompt)}</small></td>`:''}<td class="score">${r.score}</td><td contenteditable="true">${escapeHtml(r.text)}</td>${ri===0?`<td rowspan="${q.maxScore+1}" contenteditable="true">${escapeHtml(d.commonRule||'표현이 달라도 성취기준과 문항의 의도에 맞고 근거가 타당하면 인정한다.')}</td>`:''}</tr>`).join('')).join('');output.innerHTML=`<div class="rubric-title"><h2>서·논술형 평가 채점 루브릭</h2><p>${escapeHtml(d.subject)} · ${escapeHtml(d.grade)} · ${escapeHtml(d.focus)}</p></div><table class="meta-table"><tr><th>교과</th><td>${escapeHtml(d.subject)}</td><th>학년·학기</th><td>${escapeHtml(d.grade)}</td></tr><tr><th>성취기준</th><td colspan="3">${escapeHtml(d.standard)}</td></tr><tr><th>평가 내용</th><td colspan="3">${escapeHtml(d.focus)}</td></tr></table><table class="rubric-table"><thead><tr><th>문항</th><th>채점요소·문항</th><th>척도</th><th>척도별 수행 특성</th><th>유의점</th></tr></thead><tbody>${body}</tbody></table><div class="rubric-notes"><b>교사 검토 안내</b><br>문항과 수행 특성은 입력한 내용을 바탕으로 만든 초안입니다. 학생 수준과 수업에서 실제 다룬 내용에 맞는지 확인해 주세요. 입력하지 않은 사실·통계·인용은 포함하지 않았습니다.</div>`;}
form.addEventListener('input',e=>{e.target.classList.remove('invalid');saveDraft();});
form.addEventListener('submit',e=>{e.preventDefault();if(!validate())return;generated=makeQuestionDrafts(data());renderQuestions();showQuestions();});
document.querySelector('#regenerate').addEventListener('click',()=>{generated=makeQuestionDrafts(data());renderQuestions();toast('문항 초안을 다시 만들었어요.');});
document.querySelector('#backToInput').addEventListener('click',()=>{questionPanel.hidden=true;inputPanel.hidden=false;progress.forEach((p,i)=>p.classList.toggle('active',i===0));inputPanel.scrollIntoView({behavior:'smooth'});});
document.querySelector('#makeRubric').addEventListener('click',()=>{if(generated.some(q=>!q.prompt||!q.element||!q.evidence)){toast('문항의 빈칸을 확인해 주세요.');return;}latestData={...data(),questions:generated};renderRubric(latestData);resultSection.hidden=false;progress.forEach((p,i)=>p.classList.toggle('active',i===2));resultSection.scrollIntoView({behavior:'smooth'});});
document.querySelector('#editQuestions').addEventListener('click',()=>questionPanel.scrollIntoView({behavior:'smooth'}));
document.querySelector('#loadSample').addEventListener('click',()=>{setData(sample);toast('예시를 불러왔어요.');});
document.querySelector('#printRubric').addEventListener('click',()=>window.print());
document.querySelector('#exportJson').addEventListener('click',()=>{if(!latestData)return;const blob=new Blob([JSON.stringify(latestData,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${latestData.subject}_${latestData.focus}_루브릭.json`;a.click();URL.revokeObjectURL(a.href);});
try{const draft=JSON.parse(localStorage.getItem(STORAGE_KEY));if(draft)setData(draft);}catch{}
